# Generated by Django 4.2.6 on 2023-10-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_remove_order_transaction_id_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
